version: "3.9"

services:
  server:
    build: ./node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    working_dir: /app
    command: ["node", "index.js"]
    environment:
      - NODE_ENV=development

  client:
    build: ./strava-app
    ports:
      - "8080:8080"
    volumes:
      - ./strava-app:/app
    working_dir: /app
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server